# APPID
alipay.appId:
  2021000118606837
# 商户私钥, 即PKCS8格式RSA2私钥
alipay.privateKey:
  MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCWDaYZlMEvsru95A3z0QMLnV8b52SjsMHOHO5v9g/p+KzFeA4rE+EA9IbrMw/n8GfHdjQo2wnXfZ6xFIrlYDKR4H0qcTI+LTL6KVh+dnrkRnNB74FDERSeIAw3CJxCvDLcy+v0WgikDbcr+LMp23glA77IIAbjbtZjullwthdAXMrVT36L2OKXf4Hf7VZEe5sPmovhHMZRxhmcRruVL6cLltTwZeOTjzQGqjjtaZUP0+EACi4lq5Y8Ev0W6n+GNqeilmBuPiPPmCrG0QKnJgj9UZBJ7Vg+QNFJmp1PoCWrqHlCa9Y15Teb1tYSnV0fwx/EW6rWRYjqqsKR8df12415AgMBAAECggEAaR2KnCT+6EEXD8EwnPpwXbSSqeOBNsJeIdtWlQwUvdy8e2DM3BSC7L5fvWf53oskyC/f/jbjQBf6ESbI3kJzaomOZSsC/VeAfIp2ObEaCcvodeon7SmL/fGJXQwlGwLnxpD77CMeJn6NMLp6F/pswdFL1rnI2Y4NlbM3cKO+yhCc1Su2eNYAL7X3ZmtxYRkexExAu5AG6DrJpQChmJxTXw5jzl4NnoIQdd6MjXyS/f7fyK/jMmGD/k2VpKJ/SLYvdQIO8Iro/lWw88qXauBNrnCz9zqMhyIKscmZ/6rJV5Lywch1Z9EfZ6rjFZMIg2ltjejC+oAr8oMWZh7Blkhr+QKBgQD3d07PHX5sfSaxBuBnVwSYHy6QUUKpyuNw+mS9PfUwaFTxyXeiIKLnqe3Y+9+NbzrLGl+SKRsKFZti9nWOmZTNHFKDMSFaAbYRrVsBEoUOOFCvE3TKWO/SM33lIt1StKGbfymsgepK182ZyGeuRBXkhgO1bmpnXIRuRuv4+xPeHwKBgQCbOltmUzHqzT1JLbPcgyAXcLNUPAnfuS8KjOGtjABTqu5z1lKuiYIULXSvjFCmFieXHA7NRFNO78Gv0RMDfHGKhc+Ae2jnr3HjVlrVIXMslR/qCNr2j7sWuuhLO4iMRM/q0WSJ5p6fOxto1FRoMef/mARg8Jk4AD4fg4wZ5v7xZwKBgC7XSXaQuZ5lbg5yI8XLxdXZiSHOD9U9zyFSdAESGjgId5Ows9FfZhZ9psS8oEsQM8u/+TkcSL726guoZQYR8gWFB+VHRm3YBxN/gctJKyBO7o7FGwU2ImbiUkEuAUCnajOZtVSu3p8+C+/A7EcjIhW4fDk6Zi+cZoDNMdtWAyO3AoGAfQ/iTamfoP4kb03sCDB47Ym2YZpRljc7qDNjK5CNPtuLbDZzvP06mQkaZskUvQtCcGOBpW1z9TgDg6RdvkRHsgQm7uv+1BMtHa0YV3iws22eHc9uopGgeSqzNtHLLL/QB+8WImh0yfM0HRxcuOnkca/Hb1bJCy5e3sL8YG4UXucCgYBAblFzgufbWEd5lvm5N23HuJGxg3LB06hFiV/oAvIam+Gdk2GDpIzsr3NPmkD8SmVsBrfeW59lzxZA0+EJj5CMP8YfvF3PiH0tjozqq5EmppODd31G64CRAiD++YWm0agkqkTzapobWdqHLhGUHegtuXfJtdKHc4cAcvw/iNIN3Q==
# 支付宝公钥, 即对应APPID下的支付宝公钥
alipay.publicKey:
  MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDIgHnOn7LLILlKETd6BFRJ0GqgS2Y3mn1wMQmyh9zEyWlz5p1zrahRahbXAfCfSqshSNfqOmAQzSHRVjCqjsAw1jyqrXaPdKBmr90DIpIxmIyKXv4GGAkPyJ/6FTFY99uhpiq0qadD/uSzQsefWo0aTvP/65zi3eof7TcZ32oWpwIDAQAB
# 服务器异步通知页面路径, 需http://格式的完整路径
# 踩坑:不能加?type=abc这类自定义参数
alipay.notifyUrl:
# 页面跳转同步通知页面路径, 需http://格式的完整路径
# 踩坑:不能加?type=abc这类自定义参数
alipay.returnUrl:http:
  //192.168.1.4:8080/#/paySuccess
# 签名方式
alipay.signType:
  RSA2
# 字符编码格式
alipay.charset:
  utf-8
# 支付宝网关
alipay.gatewayUrl:
  https://openapi.alipaydev.com/gateway.do
# 日志打印地址
alipay.logPath:
  "E:\\"
